# Generated by Django 4.2.15 on 2025-12-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на обложку'),
        ),
    ]
